import { DEFAULT_CLIP, type Asset, type Project } from "./types";

export const DEMO_ASSETS: Asset[] = [
  {
    id: "coastal-escape",
    name: "Coastal escape.jpg",
    type: "image",
    src: "/assets/island-escape.jpg",
    thumbnail: "/assets/island-escape.jpg",
    duration: 5.5,
    category: "Travel",
  },
  {
    id: "beach-morning",
    name: "Beach morning.jpg",
    type: "image",
    src: "/assets/coast-aerial.jpg",
    thumbnail: "/assets/coast-aerial.jpg",
    duration: 5.5,
    category: "Travel",
  },
  {
    id: "palm-paradise",
    name: "Palm paradise.jpg",
    type: "image",
    src: "/assets/golden-hour.jpg",
    thumbnail: "/assets/golden-hour.jpg",
    duration: 5,
    category: "Travel",
  },
  {
    id: "bali-temple",
    name: "Bali temple.jpg",
    type: "image",
    src: "/assets/bali-temple.jpg",
    thumbnail: "/assets/bali-temple.jpg",
    duration: 5,
    category: "Travel",
  },
  {
    id: "ocean-waves",
    name: "Ocean waves.jpg",
    type: "image",
    src: "/assets/ocean-waves.jpg",
    thumbnail: "/assets/ocean-waves.jpg",
    duration: 5,
    category: "Travel",
  },
  {
    id: "tropical-beach",
    name: "Island hideaway.jpg",
    type: "image",
    src: "/assets/tropical-beach.jpg",
    thumbnail: "/assets/tropical-beach.jpg",
    duration: 5,
    category: "Travel",
  },
  {
    id: "tropical-daydream",
    name: "Tropical daydream",
    type: "audio",
    src: "/assets/tropical-daydream.wav",
    thumbnail: "",
    duration: 16,
    category: "Chill",
  },
  {
    id: "sunlit-mornings",
    name: "Sunlit mornings",
    type: "audio",
    src: "/assets/sunlit-mornings.wav",
    thumbnail: "",
    duration: 24,
    category: "Acoustic",
  },
  {
    id: "ocean-hush",
    name: "Ocean hush",
    type: "audio",
    src: "/assets/ocean-hush.wav",
    thumbnail: "",
    duration: 16,
    category: "Sound effects",
  },
];

export function createDemoProject(): Project {
  return {
    name: "Bali, a little closer",
    aspectRatio: "16:9",
    background: "#101113",
    assets: DEMO_ASSETS.map((asset) => ({ ...asset })),
    clips: [
      ...DEMO_ASSETS.slice(0, 3).map((asset, index) => ({
        ...DEFAULT_CLIP,
        id: `demo-clip-${index}`,
        assetId: asset.id,
        name: asset.name,
        type: asset.type,
        src: asset.src,
        thumbnail: asset.thumbnail,
        start: index * 5.5,
        duration: asset.duration,
        track: 0,
      })),
      {
        ...DEFAULT_CLIP,
        id: "demo-title",
        name: "A little closer to paradise.",
        type: "text",
        src: "",
        start: 0,
        duration: 5.5,
        track: 1,
        text: "A little closer\nto paradise.",
        fontSize: 66,
        fontFamily: "Inter",
        bold: true,
        x: 0,
        y: 0,
      },
      {
        ...DEFAULT_CLIP,
        id: "demo-music",
        assetId: "tropical-daydream",
        name: "Tropical daydream",
        type: "audio",
        src: "/assets/tropical-daydream.wav",
        start: 0,
        duration: 16,
        track: 2,
        volume: 45,
        fadeIn: 0.7,
        fadeOut: 1.5,
      },
    ],
  };
}
